### ISSUE TITLE
make release fails in 19.06 release

### ISSUE THREAD

**Issue by akhilerm** [Seagate/openSeaChest#19]
`make release` fails in Release-19.06, with the following error 
```
make: *** No rule to make target '../../src/seachest_util_options.o', needed by 'openSeaChest_NVMe'.  Stop.
```
Platform:
```
uname -a
Linux MayaData 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by akhilerm** [comment]
Fixed in #20 

Will there be a new dot release with the fix?

**Comment by vonericsen** [comment]
@akhilerm, there is no current plan for a new release since there hasn't been a change to the tools themselves.
I merged this fix into our master branch which is more stable and is supposed to contain release code.
I can add a tag if you would like to reference that. There is already one named "Hotfix-Makefile_Fix", but I can create one called something like "Release-19.06.01" if that would be better.

**Comment by akhilerm** [comment]
@vonericsen That would be great. A tag like `Release-19.06.01` will be much cleaner if we reference from other repos. Can you proceed with creating that tag?

**Comment by vonericsen** [comment]
@akhilerm I am sorry for the delay creating the tag, but it has been created and pushed!
The tag was created as: `Release-19.06.01` on openSeaChest.git master branch with the makefile fixes.

**Comment by akhilerm** [comment]
Thanks @vonericsen .
