### ISSUE TITLE
Feature Request: Traditional Linux-style device files in Linux

### ISSUE THREAD

**Issue by BillyCrook** [Seagate/openSeaChest#26]
I understand that the sg driver is capable of more than sd driver, and that it's indeed necessary to work with sg in order to do most of the things that openSeaChest does.

But nobody else, and no other tools in common use in linux touch the sg objects by their /dev/sg# name.  I know the sg's exist, but I'm hard pressed to think of the last time I ever referenced them.  So I conject that it causes unnecessary confusion and takes unnecessary time to translate between sd* and sg* objects for the user.

Can openSeaChest default to displaying sd* drive names in linux?  Or offer it as a command-line flag?

**Comment by vonericsen** [comment]
Hi @BillyCrook,
In openSeaChest, you can display the handles with the block handles (hard drives only, may not work properly on tapes, cds, etc) adding  _-F sd_ on the command line, so there's already a way to do this today.
There is also an option to show the relationship between sd and sg adding _-F sgtosd_ to be similar to the output of _lsscsi -g_.
Full example: _openSeaChest_Basics -s -F sd_

Now, the difference between SG and SD is that SD is a block handle, really only meant for read/write and SG is a generic interface to send any commands you want.
You can specify /dev/sd? handles to these tools as well as other opensource tools without an issue because of the mapping provided by the Linux kernel, version 2.7+. In earlier versions of the kernel, this mapping was not available so only SG could be used for SG passthrough and SD for read/write and possibly other legacy methods.
The main reason openSeaChest defaults to SG instead of SD is because of customer reported problems with the power control tools to show the current power mode.
Whenever the handle was opened as /dev/sd?, the drive would be spun up, but this did not happen with /dev/sg? to the same device. When I debugged this issue with a SATA bus analyzer, I found that there were other commands being sent to the drive and spinning it up at the call to open the handle. The best reason I could come up for this behavior is that because SD is a block handle, meant for read and write, the OS was making sure the drive is in an active state and ready to process any further read/write commands as quickly as possible.
The solution that I came up with for this issue is when a /dev/sd? handle is received, openSeaChest will map it to the matching /dev/sg? handle on the system using the sysfs.
