### ISSUE TITLE
With disk permissions, -s gives warning but does not output data without root access/sudo

### ISSUE THREAD

**Issue by natanlidukhover** [Seagate/openSeaChest#39]
After a recent change, with disk access, openSeaChest now outputs drive data with the -i flag without root/sudo while only producing a warning rather than an error. However, even with disk permissions, when running a scan with -s, a warning is still produced but no data is outputted unless run with root/sudo.

**Comment by vonericsen** [comment]
After debugging and looking through the code, the problem was found to be that some enclosures in the system still needed root for access to them.
With the previous code changes, the problem was the scan was returning PERMISSION_DENIED when any /dev/sg handle returned a permissions error when opening it.
I changed it to only returning this if ALL devices in the system return permissions errors, this way the tools will show what devices were able to be accessed otherwise.
This change was applied to all OSs we have support for to make sure there is consistent behavior.
