### ISSUE TITLE
Encryption & PSID

### ISSUE THREAD

**Issue by Xanth0k1d** [Seagate/openSeaChest#89]
I bought a few st1000lm035 hard drives, I noticed that they all have PSIDs, but with deviceInfo, I realised that encryption is not supported.
Why is this so? Can I switch to a firmware supporting encryption or are these drives unable to support encryption?(If so, then why do they all have PSID?)

**Comment by vonericsen** [comment]
Hi @Xanth0k1d,

All Seagate drives come with PSIDs for a many years now as all Seagate products come with SD&D (Secure Downloads and Diagnostics) enabled on all firmware's to provide security better security for every drive made. This blocks access to the internal diagnostics outside of Seagate and adds more validation to make sure any firmware is authentic from Seagate so that it is not possible to flash a non-Seagate firmware to the drive.

This document has some more information about the [SD&D feature](https://www.seagategov.com/seagategov-content/product/maximize-security-lock-down-hard-drive-firmware-with-seagate-secure-download&diagnostics.pdf).

**Comment by Xanth0k1d** [comment]
Hi @vonericsen ,
Thank you for the information. 
The Seagate brochure for that family of drives also indicates that ST1000LM035 is the base model and not an SED.
Can it be said that the PSID on the drive label had nothing to do with drive content encryption?

**Comment by vonericsen** [comment]
> Can it be said that the PSID on the drive label had nothing to do with drive content encryption?

For Seagate drives, this is a correct statement. I'm not sure if this would apply to other vendors.
